import { ThemeConfig } from "vuepress-theme-vt";
import { defineConfig4CustomTheme } from "vuepress/config";

export = defineConfig4CustomTheme<ThemeConfig>((ctx) => ({
  theme: "vt",
  title: "ECG Color Stability",
  base: "/vuepress-test/",
  themeConfig: {
    enableDarkMode: true,
    repo: "https://github.com/matthewfurr/vuepress-test",
    logo: "/logo.svg",
    smoothScroll: true,
    editLinks: true,
    editLinkText: 'Sarah, click me to edit!',
    nav: [
      { text: "Intro", link: "/intro/" },
      { text: "Lit Review", link: "/litreview/" },
      { text: "Methodology", link: "/methodology/" },
      { text: "Results", link: "/results/" },
    ],
    sidebar: {
      "/intro/": [
        {
          title: "Introduction",
          collapsable: false,
          children: [
            "/intro/",
            "/intro/background",
            "/intro/purpose",
            "/intro/research-questions",
            "/intro/hypothesis",
            "/intro/assumptions-limitations",
            "/intro/contributions",
            "/intro/definition-of-terms",
          ],
        },
        {
          title: "Literature Review",
          collapsable: true,
          children: [
            "/litreview/",
            "/litreview/color-theory",
            "/litreview/tone-reproduction",
            "/litreview/color-reproduction",
            "/litreview/color-management",
            "/litreview/expanded-gamut",
            "/litreview/flexography",
            "/litreview/measurement",
          ],
        },
        {
          title: "Methodology",
          collapsable: true,
          children: [
            "/methodology/",
            "/methodology/material-selection",
            "/methodology/fingerprinting",
            "/methodology/characterization",
            "/methodology/dataset-selection",
            "/methodology/chart-generation",
            "/methodology/variation",
            "/methodology/measurements",
            "/methodology/calculations",
          ],
        },
        {
          title: "Results",
          collapsable: true,
          children: [
            "/results/",
            "/results/comparisons",
            "/results/gray-component-replacement",
            "/results/anova",
            "/results/conclusion",
            "/results/implications",
            "/results/recommendations",
          ],
        },
        {
          title: "References",
          collapsable: true,
          children: [ "/references/" ],
        },
      ],
      "/litreview/": [
        {
          title: "Introduction",
          collapsable: true,
          children: [
            "/intro/",
            "/intro/background",
            "/intro/purpose",
            "/intro/research-questions",
            "/intro/hypothesis",
            "/intro/assumptions-limitations",
            "/intro/contributions",
            "/intro/definition-of-terms",
          ],
        },
        {
          title: "Literature Review",
          collapsable: false,
          children: [
            "/litreview/",
            "/litreview/color-theory",
            "/litreview/tone-reproduction",
            "/litreview/color-reproduction",
            "/litreview/color-management",
            "/litreview/expanded-gamut",
            "/litreview/flexography",
            "/litreview/measurement",
          ],
        },
        {
          title: "Methodology",
          collapsable: true,
          children: [
            "/methodology/",
            "/methodology/material-selection",
            "/methodology/fingerprinting",
            "/methodology/characterization",
            "/methodology/dataset-selection",
            "/methodology/chart-generation",
            "/methodology/variation",
            "/methodology/measurements",
            "/methodology/calculations",
          ],
        },
        {
          title: "Results",
          collapsable: true,
          children: [
            "/results/",
            "/results/comparisons",
            "/results/gray-component-replacement",
            "/results/anova",
            "/results/conclusion",
            "/results/implications",
            "/results/recommendations",
          ],
        },
        {
          title: "References",
          collapsable: true,
          children: [ "/references/" ],
        },
      ],
      "/methodology/": [
        {
          title: "Introduction",
          collapsable: true,
          children: [
            "/intro/",
            "/intro/background",
            "/intro/purpose",
            "/intro/research-questions",
            "/intro/hypothesis",
            "/intro/assumptions-limitations",
            "/intro/contributions",
            "/intro/definition-of-terms",
          ],
        },
        {
          title: "Literature Review",
          collapsable: true,
          children: [
            "/litreview/",
            "/litreview/color-theory",
            "/litreview/tone-reproduction",
            "/litreview/color-reproduction",
            "/litreview/color-management",
            "/litreview/expanded-gamut",
            "/litreview/flexography",
            "/litreview/measurement",
          ],
        },
        {
          title: "Methodology",
          collapsable: false,
          children: [
            "/methodology/",
            "/methodology/material-selection",
            "/methodology/fingerprinting",
            "/methodology/characterization",
            "/methodology/dataset-selection",
            "/methodology/chart-generation",
            "/methodology/variation",
            "/methodology/measurements",
            "/methodology/calculations",
          ],
        },
        {
          title: "Results",
          collapsable: true,
          children: [
            "/results/",
            "/results/comparisons",
            "/results/gray-component-replacement",
            "/results/anova",
            "/results/conclusion",
            "/results/implications",
            "/results/recommendations",
          ],
        },
        {
          title: "References",
          collapsable: true,
          children: [ "/references/" ],
        },
      ],
      "/results/": [
        {
          title: "Introduction",
          collapsable: true,
          children: [
            "/intro/",
            "/intro/background",
            "/intro/purpose",
            "/intro/research-questions",
            "/intro/hypothesis",
            "/intro/assumptions-limitations",
            "/intro/contributions",
            "/intro/definition-of-terms",
          ],
        },
        {
          title: "Literature Review",
          collapsable: true,
          children: [
            "/litreview/",
            "/litreview/color-theory",
            "/litreview/tone-reproduction",
            "/litreview/color-reproduction",
            "/litreview/color-management",
            "/litreview/expanded-gamut",
            "/litreview/flexography",
            "/litreview/measurement",
          ],
        },
        {
          title: "Methodology",
          collapsable: true,
          children: [
            "/methodology/",
            "/methodology/material-selection",
            "/methodology/fingerprinting",
            "/methodology/characterization",
            "/methodology/dataset-selection",
            "/methodology/chart-generation",
            "/methodology/variation",
            "/methodology/measurements",
            "/methodology/calculations",
          ],
        },
        {
          title: "Results",
          collapsable: false,
          children: [
            "/results/",
            "/results/comparisons",
            "/results/gray-component-replacement",
            "/results/anova",
            "/results/conclusion",
            "/results/implications",
            "/results/recommendations",
          ],
        },
        {
          title: "References",
          collapsable: true,
          children: [ "/references/" ],
        },
      ],
    },
  },
}));
